services:
  payload:
    # Use the image but override the command for Live Development
    image: node:22.17.0-slim
    working_dir: /app
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules # Prevents host modules from clashing
      - /app/.next        # Prevents host build from clashing
    # This installs and starts the dev server every time you run the container
    command: bash -c "corepack enable pnpm && pnpm i && pnpm dev"
